### ISSUE TITLE
Deleting a draft boarding causes a crash

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#444]
**Describe the bug**
When trying to delete a draft boarding, the app crashes. The draft boarding is not deleted.

**To Reproduce**
1. Create a draft, save it.
2. Click on the draft boardings icon on the home screen and choose a draft to edit.
3. Click the "X" at the top right
4. click "Delete Boarding" - crash occurs here.

**Expected behavior**
I expect the boarding to save, draft boardings now show a decrement (or nothing if there was 1 draft before and now there is none).

Error message:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wildaid.ofish.debug, PID: 485
    io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
        at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:541)
        at io.realm.Realm.executeTransaction(Realm.java:1533)
        at org.wildaid.ofish.data.RealmDataSource.deleteDraft(RealmDataSource.kt:186)
        at org.wildaid.ofish.data.RepositoryImpl.deleteDraft(RepositoryImpl.kt:149)
        at org.wildaid.ofish.ui.createreport.CreateReportViewModel.deleteReport(CreateReportViewModel.kt:42)
        at org.wildaid.ofish.ui.createreport.CreateReportActivity.handleDialogClick(CreateReportActivity.kt:131)
        at org.wildaid.ofish.ui.createreport.CreateReportActivity.subscribeToDialogEvents$lambda-0(CreateReportActivity.kt:59)
        at org.wildaid.ofish.ui.createreport.CreateReportActivity.lambda$StAcqdYSFIqcMlZzPRxPRdTiN5s(Unknown Source:0)
        at org.wildaid.ofish.ui.createreport.-$$Lambda$CreateReportActivity$StAcqdYSFIqcMlZzPRxPRdTiN5s.onStateChanged(Unknown Source:4)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:118)
        at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.java:150)
        at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.java:130)
        at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.java:487)
        at androidx.navigation.NavController.popBackStack(NavController.java:280)
        at androidx.navigation.NavController.popBackStack(NavController.java:264)
        at androidx.navigation.fragment.DialogFragmentNavigator$1.onStateChanged(DialogFragmentNavigator.java:63)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2892)
        at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:391)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1223)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/chatty: uid=10086(org.wildaid.ofish.debug) identical 1 line
E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted
I/Process: Sending signal. PID: 485 SIG: 9

Additional notes:
I can do a regular boarding and cancel it with no problems.

**Comment by mohit-sharma-87** [comment]
@Sheeri : I think so this issue can be found in other area's as well like, 

1. saveOnDutyChange
2. updateStartDateForCurrentDuty
3. savePhoto

So the impact area of this ticket will increase, kindly confirm changes are needed will be in the same ticket or different?

**Comment by Sheeri** [comment]
You can do it in the same ticket!

**Comment by Sheeri** [comment]
All set, the other areas are done as well.
